BookStore3/bookStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    # Administration
    path('admin/', admin.site.urls),

    # User authentication
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    # Navigation
    # home page

    path('books/', include('books.urls')),
    path('', include('search.urls')),
    # path('', include('books.urls')),

    # user profile setting page which will include security, user information, and billing
    path('settings/', include('users.urls', namespace='settings')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookStore3/books/urls.py
from django.urls import path
from . import views
from .views import BookDetailView, AuthorBookListView

urlpatterns = [
    # path('', BookListView.as_view(), name='book-browsing'),
    path('', views.index, name='book-browsing'),
    path('<int:pk>/', BookDetailView.as_view(), name='book-details'),
    path('user/<username>', AuthorBookListView.as_view(), name='author-browsing'),  
    path('booksPurchased/<int:id>/', views.ReviewView, name='book-details-purchased'),  
]

BookStore3/users/urls.py
from django.urls import path, include   # path is to create the path in urlpatterns
from . import views # Import the views defined in the current directory

# Name of the app needed for the namespace on urls.py
app_name = 'settings'

# all settings urls!!!
urlpatterns = [
    path('', views.settingsHome, name='settings-home'),
    path('profile/', views.profile, name='profile-settings'),
    path('account/', views.accountSettings, name='account-settings'),
    path('billing/', views.billingSettings, name='billing-settings'),
    path('billing/address/new/', views.addAddress, name='add-address'),
    path('billing/address/<slug:address_slug>/', views.addressChange, name='edit-address'),
    path('billing/creditcard/new/', views.addCreditCard, name='add-creditcard'),
    path('billing/creditcard/<slug:creditcard_slug>/', views.creditCardChange, name='edit-creditcard'),
    path('security/', views.securitySettings, name='security-settings')
]

BookStore3/users/models.py
from django.db import models, transaction
from django.contrib.auth.models import User
from localflavor.us.models import USStateField  # To shows list of US states on address form
from django.urls import reverse # to return url when clicking on address
from .calendar import MONTHS, YEARS, JAN, CURRENT_YEAR

# https://docs.djangoproject.com/en/2.1/ref/models/instances/#get-absolute-url

# All data is linked to this profile. If data gets deleted then the user should be deleted as well
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nick_name = models.CharField('Nick name', max_length=30, blank=True, default='')
    bio = models.TextField(max_length=450, blank=True)

    def __str__(self):
        # get the profile not just the object
        return self.user.username


# All information for the address should be linked to this
class Address(models.Model):
    name = models.CharField(max_length=50, blank=False)
    address1 = models.CharField("Address Lines 1", max_length=100)
    address2 = models.CharField("Address Lines 2", max_length=100, blank=True)
    city = models.CharField("City", max_length=50)
    state = USStateField("State", default='FL')
    zipcode = models.CharField("Zipcode", max_length=5)
    slug = models.SlugField(max_length=150, db_index=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False)
    primaryAddress = models.BooleanField()

    def __str__(self):
        return self.name

    @transaction.atomic
    # if primary address is checked
    def save(self, *args, **kwargs):
        if self.primaryAddress:
            Address.objects.filter(
                primaryAddress=True).update(primaryAddress=False)
        super(Address, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('settings:edit-address', args=[self.id])

# all credit card information should be linked to this
class CreditCard(models.Model):
    name = models.CharField(max_length=50, blank=False)
    number = models.CharField(max_length=16, blank=False, unique=True)
    expdate_month = models.IntegerField(choices=MONTHS, default=JAN)
    expdate_year = models.IntegerField(choices=YEARS, default=CURRENT_YEAR)
    securitycode = models.IntegerField(blank=False)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('settings:edit-creditcard', args=[self.id])

BookStore3/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import UserSignUpForm, UserUpdateForm, UserProfileForm, BioForm, NicknameForm, EditAddressForm, DeleteAddressForm, CreditCardForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import PasswordChangeForm
from .models import Address, CreditCard

# https://simpleisbetterthancomplex.com/tips/2016/08/04/django-tip-9-password-change-form.html
# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.htmls

# User registration page
def signup(request):
    # If the request is a post, then proceed w/ the form
    if request.method == 'POST':
        form = UserSignUpForm(request.POST)
        # To validate the form if the form is valid
        if form.is_valid():
            # save the form
            form.save()
            # obtain the username
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account successfully created for { username }.')
            # redirect to the store home page which is bookdetails page
            return redirect('/login')
            # return redirect ('store-home-page')
    # if the request is not a post, then show a blank form
    else:
        # to use the form at signup we create an instance of the form we imported on top:
        form = UserSignUpForm()
    return render(request, 'users/signup.html', {'form': form})

# When the user clicks on the profile menu, he/she will be redirected here
@login_required
def settingsHome(request):
    return redirect('settings:profile-settings')

#  This is to update the profile page, so users can add name, bio and nickname
@login_required
def profile(request):
    if request.method == 'POST':
        # Get first name and last name from User Profile Form
        userProfileForm = UserProfileForm(request.POST, instance=request.user)
        # Get Bio information from users
        userBioForm = BioForm(request.POST, instance=request.user.profile)
        # Get Nickname Information from users
        userNicknameForm = NicknameForm(request.POST, instance=request.user.profile)

        # if everything inputed is valid then update form
        if userProfileForm.is_valid() and userBioForm.is_valid() and userNicknameForm.is_valid():
            # save the profile form
            userProfileForm.save()
            # save the bio form
            userBioForm.save()
            # save the nickname form
            userNicknameForm.save()
            messages.success(request, f'Your profile updated successfully!')
            return HttpResponseRedirect(request.path_info)
        else:
            messages.warning(request, f'There were errors updating you profile.')

    else:
        # just get user information
        userProfileForm = UserProfileForm(instance=request.user)
        userBioForm = BioForm(instance=request.user.profile)
        userNicknameForm = NicknameForm(instance=request.user.profile)

    context = {
        'userProfileForm': userProfileForm,
        'userBioForm': userBioForm,
        'userNicknameForm': userNicknameForm
    }

    # return to profile page
    return render(request, 'users/profile.html', context)


# This form is to update the username and email
@login_required
def accountSettings(request):
    if request.method == 'POST':
        userForm = UserUpdateForm(request.POST, instance=request.user)

        # get form validation
        if userForm.is_valid():
            # save the form
            userForm.save()
            # print success message
            messages.success(request, f'Account updated successfully!')
            return HttpResponseRedirect(request.path_info)
        # else incorrect inputs
        else:
            messages.warning(request, f'ERROR!')

    else:
        userForm = UserUpdateForm(instance=request.user)

    context = {
        'userForm': userForm
    }
    return render(request, 'users/account.html', context)

# This part involves everything for billing such ass address and credit card
# *****************************************************************************************************
# Billing page (credit card and billing address)
@login_required
def billingSettings(request):

    primaryAddressCheck = False
    # Get user address list
    userAddressList = Address.objects.all().filter(user__user__username=request.user)
    userCreditCards = CreditCard.objects.all().filter(user__user__username=request.user)

    for address in userAddressList:
        if address.primaryAddress == True:
            primaryAddressCheck = True

    context = {
        'userAddressList': userAddressList,
        'primaryAddressCheck': primaryAddressCheck,
        'userCreditCards': userCreditCards,
    }

    return render(request, 'users/billing.html', context)

# This is to add a new address to the users, it can either be primary or not
@login_required
def addAddress(request):

    if request.method == 'POST':
        userAddressForm = EditAddressForm(request.POST)

        # if new address meets all required fields
        if userAddressForm.is_valid():
            # store the new address as new address
            newUserAddress = userAddressForm.save(commit=False)
            newUserAddress.user_id = request.user.profile.id
            newUserAddress.save()
            # if message saved then
            messages.success(request, f'New Address has Been Added')
            return redirect('settings:billing-settings')
        else:
            messages.warning(
                request, f'ERROR! Please check all Fields!')

    else:
        userAddressForm = EditAddressForm()

    context = {
        'userAddressForm': userAddressForm
    }

    return render(request, 'users/addAddress.html', context)


# This is to update the current address
@login_required
def addressChange(request, address_slug):

    # Gets all the fields of the current address based on id
    currentAddress = Address.objects.all().get(pk=address_slug)

    if request.method == 'POST':
        userAddressForm = EditAddressForm(request.POST, instance=currentAddress)

        # check to see if all fields are valid
        if userAddressForm.is_valid():
            userAddressForm.save()
            messages.success(request, f'Your Address Updated successfully')
            # stay in the same directory after updating
            return HttpResponseRedirect(request.path_info)
        # this is to delete the current address
        elif DeleteAddressForm():
            Address.objects.filter(id=address_slug).delete()
            return redirect('settings:billing-settings')
        else:
            messages.warning(request, f'There errors updating you profile. Please check all Fields!')

    else:
        userAddressForm = EditAddressForm(instance=currentAddress)

    context = {
        'address_slug': address_slug,
        'userAddressForm': userAddressForm,
    }
    return render(request, 'users/addressChange.html', context)

# this is to add a new credit card
@login_required
def addCreditCard(request):

    if request.method == 'POST':
        userCreditCardForm = CreditCardForm(request.POST)

        # check if form is valid
        if userCreditCardForm.is_valid():
            # save the current inputs from the user
            newCreditCard = userCreditCardForm.save(commit=False)
            newCreditCard.user_id = request.user.profile.id
            newCreditCard.save()
            # if credit card added successfully then redirect to billing page
            messages.success(request, f'Your Credit Card has been Added!')
            return redirect('settings:billing-settings')
        else:
            messages.warning(
                request, f'Error in Adding your Credit Card!')
    else:
        userCreditCardForm = CreditCardForm()

    context = {
        'userCreditCardForm': userCreditCardForm
    }
    # render the page to add a credit card
    return render(request, 'users/addCreditCard.html', context)

# to update/edit your current credit card
@login_required
def creditCardChange(request, creditcard_slug):

    # Gets the current credit card you want to edit based on ID
    currentCreditCard = CreditCard.objects.all().get(pk=creditcard_slug)

    if request.method == 'POST':
        # save the current changes to this credit card
        userCreditCardForm = CreditCardForm(request.POST, instance=currentCreditCard)

        # check if the form is valid
        if userCreditCardForm.is_valid():
            # save the current changes
            userCreditCardForm.save()
            messages.success(request, f'Credit Card has Been Updated!')
            # do not redirect to new page, stay in same page
            return HttpResponseRedirect(request.path_info)

        # if you want to delete this credit card
        elif 'delete' in request.POST:
            currentCreditCard.delete()
            # redirect to billing page after deleting
            return redirect('settings:billing-settings')

        else:
            messages.warning(request, f'Error in Updating Credit Card.')
    else:
        userCreditCardForm = CreditCardForm(instance=currentCreditCard)

    context = {
        'creditcard_slug': creditcard_slug,
        'userCreditCardForm': userCreditCardForm,
    }
    return render(request, 'users/creditCardChange.html', context)


#*****************************************************************************************************

# To update users password
@login_required
def securitySettings(request):
    if request.method == 'POST':
        passform = PasswordChangeForm(request.user, request.POST)

        # if the passwords match then update it
        if passform.is_valid():
            passform.save()
            # update users password with new password

BookStore3/users/templates/users/account.html
<!--Here I got the base from user base because all of these new pages will be directly under the 4 buttons-->
{% extends "users/partials/_base.html" %}
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block settingsPageInfo %}

<!--This page is to see the users current username and email address and is allowed to update it-->
<div class="card bg-dark text-primary" style="text-align:center;vertical-align:middle; margin:auto;">
    <div class="card-body ">
        <div class="col-md-12 border-bottom pt-4 border-success" style = "padding-bottom: 15px;">
            <h3 class="text-success">User Settings</h3>
        </div>
    </div>
    <div class = "container">
        <!--use crispy form to get all attributes from user. less coding-->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
        {{ userForm|crispy }}
        <div class="form-group">
            <!--Click to update form-->
            <button class="btn btn-outline-success" type="submit">Update</button>
        </div>

        </form>
    </div>
</div>

{% endblock %}

BookStore3/users/templates/users/addAddress.html
<!--Here I got the base from user base because all of these new pages will be directly under the 4 buttons-->
{% extends "users/partials/_base.html" %}
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block settingsPageInfo %}

<!--This form is to add a new address to the user once the tab is clicked to add a new address-->
<div class="card bg-dark text-primary">

    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-success">Add a New Address</h3>
                <hr>
            </div>
        </div>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{userAddressForm |crispy}}
            <div class="form-group">
                <!--Click button to add a new address to the user-->
                <button class="btn btn-outline-success" type="submit">Add address</button>
            </div>
        </form>

    </div>
</div>

{% endblock %}

BookStore3/users/templates/users/addCreditCard.html
<!--Here I got the base from user base because all of these new pages will be directly under the 4 buttons-->
{% extends "users/partials/_base.html" %}
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block settingsPageInfo %}

<!-- This form is to add a new cred card to the user once the tab is clicked to add a new credit card -->
<div class="card bg-dark text-primary">

    <div class="card-body" >
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-success">Add a new Credit Card</h3>
                <hr>
            </div>
        </div>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{userCreditCardForm |crispy}}
            <div class="form-group">
                 <!--Click button to add a new address to the user-->
                <button class="btn btn-outline-success" type="success">Add Credit Card</button>
            </div>
        </form>

    </div>
</div>

{% endblock %}

BookStore3/users/templates/users/addressChange.html
<!--Here I got the base from user base because all of these new pages will be directly under the 4 buttons-->
{% extends "users/partials/_base.html" %}
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block settingsPageInfo %}

<!-- This page will update the current address when clicked, your old address should display and you can either
    update it or delete it
 -->
<div  class="card bg-dark text-primary">
    <div class="card-body">

        <div class="row">
            <div class="col-md-12">
                <h3 class="text-success">Edit Your Address</h3>
                <hr>
            </div>
        </div>

        <!-- Update the current address -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{userAddressForm |crispy}}
            <div class="form-group">
                <button class="btn btn-outline-success" type="submit">Save changes</button>
            </div>
        </form>

        <!-- Delete the current address -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{DeleteAddressForm |crispy}}
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Delete</button>
            </div>
        </form>

    </div>
</div>

{% endblock %}

BookStore3/users/templates/users/billing.html
<!--Here I got the base from user base because all of these new pages will be directly under the 4 buttons-->
{% extends "users/partials/_base.html" %}
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block settingsPageInfo %}


<!-- This page will show the billing tab, this page will have two sections, one to display all the users address
    and another one to display all the users credit cards.
-->
<div class="card-body bg-dark text-primary" style="text-align:center;vertical-align:middle; margin:auto;">
    <div class="row">
        <div class="col-md-12 border-bottom pt-4 border-success" style = "padding-bottom: 15px;">
            <h3 class="text-success">Billing Information</h3>
        </div>
    </div>
    <br>
    <!-- Navbar Menu to switch between addresses and credit card info -->
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-addresses-tab" data-toggle="tab" href="#nav-addresses" role="tab"
                aria-controls="nav-addresses" aria-selected="true">Your Addresses</a>
            <a class="nav-item nav-link" id="nav-payment-tab" data-toggle="tab" href="#nav-payment" role="tab"
                aria-controls="nav-payment" aria-selected="false">Your Credit Card Info</a>
        </div>
    </nav>

    <!-- This section will display all the users primary addresses even if you switch between tabs-->
    <div class="card-body">
        <div class="card">
            <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
                <div class="card-body bg-dark text-primary">
                    <!-- Loop through all the primary addresses and display it on the website -->
                    {% if primaryAddressCheck is True %}
                        <h4 class="text-success">My Primary Address</h4>
                        {% for address in userAddressList %}
                            <!-- get all addresses from address list that have primary check -->
                            {% if address.primaryAddress is True %}
                                <br>
                                <h6 class="card-subtitle mb-2 text-info">{{ address.name }}</h6>
                                <div class="row text-white">
                                    <!-- Print out the address using this format -->
                                    <div class="col-lg-12">
                                        {{ address.address1 }}, {{ address.address2 }}
                                        <br>
                                        {{ address.state }}, {{ address.zipcode }}
                                        <div class="float-right">
                                            <a href="{{ address.get_absolute_url }}">Edit</a>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    <!-- If there are no primary address added then display this message -->
                    {% else %}
                        <h5 class="text-danger">Primary Address Has Not Been Set!</h5>
                    {% endif %}
                </div>
            </div>
        </div>

        <br>

        <!-- When address tab is pressed, then display all the users address that are not primary addresses -->
        <div class="tab-content " id="nav-tabContent">
            <!-- Address tab -->
            <div class="tab-pane fade show active" id="nav-addresses" role="tabpanel" aria-labelledby="nav-addresses-tab">
                <br>
                <h6 class="text-secondary"> My Other shipping address</h6>
                <!-- for all addresses in address list print users address that are not primary -->
                {% for address in userAddressList %}
                    {% if address.primaryAddress is False %}
                    <div class="card">
                        <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
                            <div class="card-body bg-dark">
                                <h6 class="card-subtitle mb-2 text-info">{{ address.name }}</h6>
                                <div class="row text-white">
                                    <div class="col-lg-12">
                                        {{ address.address1 }}, {{ address.address2 }}
                                        <br>
                                        {{ address.state }}, {{ address.zipcode }}
                                        <div class="float-right">
                                            <a href="{{ address.get_absolute_url }}">Edit</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    {% endif %}
                {% endfor %}

                <!-- Button to add a new address, will redirect you to a new page -->
                <a type="button" class="btn btn-outline-danger float-left" style="margin-bottom: 10px;"
                   href="{% url 'settings:add-address' %}">
                    Add New Address
                </a>
            </div>

            <!-- When your credit card tab is pressed then show all the users credit card information -->
            <div class="tab-pane fade" id="nav-payment" role="tabpanel" aria-labelledby="nav-payment-tab">
                <br>
                <h6 class="text-secondary"> My Credit Card Info</h6>

                <!-- No condition statement, just print all credit cards -->
                {% for creditcard in userCreditCards %}
                    <div class="card">
                        <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
                            <div class="card-body bg-dark">
                                <h6 class="card-subtitle mb-2 text-info">{{ creditcard.name }}</h6>
                                <div class="row text-white">
                                    <!-- Print credit cards using this format -->
                                    <div class="col-lg-12">
                                        Number: {{ creditcard.number }}
                                        <br>
                                        Expires: {{ creditcard.expdate_month }}/ {{ creditcard.expdate_year }}
                                        <div class="float-right">
                                            <a href="{{ creditcard.get_absolute_url }}">Edit</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                {% endfor %}

                <!-- Button to add a new credit card, will redirect you to a new page -->
                <a type="button" class="btn btn-outline-danger float-left" style="margin-bottom: 10px;"
                    href="{% url 'settings:add-creditcard' %}">
                    Add New Credit Card
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

BookStore3/users/templates/users/creditCardChange.html
<!--Here I got the base from user base because all of these new pages will be directly under the 4 buttons-->
{% extends "users/partials/_base.html" %}
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block settingsPageInfo %}

<!-- This page will update the current credit card when clicked, your old credit cards should display and you can either
    update it or delete it
 -->
<div class="card bg-dark text-primary">
    <div class="card-body">

        <div class="row">
            <div class="col-md-12">
                <h3 class="text-success">Edit your Credit Card</h3>
                <hr>
            </div>
        </div>

        <!-- Update the current address -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{userCreditCardForm |crispy}}
            <div class="form-group">
                <button class="btn btn-outline-success" type="submit" name="save_changes">Save changes</button>
            </div>
        </form>

        <!-- Delete the current address -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{DeleteCreditCardConfirmation |crispy}}
            <div class="form-group">
                <button class="btn btn-danger" type="submit" name="delete">Delete</button>
            </div>
        </form>

    </div>
</div>

{% endblock %}

BookStore3/users/templates/users/login.html
<!-- This will inherit from the __base.html located in this directory -->
<!-- The navbar will be located here -->
{% extends "storePage/partials/__base.html" %}
<!-- This is the main header and footer that all html will fallow by -->
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block body %}

<!-- This page will allow the user to log in to their account -->
<div class="container">
    <div class="row">
        <div class="col-md-5 mx-auto">
            <div id="first">
                <div class="myform form " style = "margin-top:35px">
                    <!-- Get username and password -->
                    <form method="POST" name="login">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form|crispy }}
                        </div>
                        <div class="col-md-12 text-center ">
                            <!-- if account found then log in and redirect them to bookstore page -->
                            <button type="submit" class=" btn btn-block mybtn btn-light tx-tfm" style = "margin-top: 40px">
                                Login
                            </button>
                        </div>
                        <!-- If user does not have an account then redirect them to sign up page -->
                        <div class="form-group text-center" style = "margin-top: 35px;">
                            <p>Would you like to create an account? </p>
                            <a href="{% url 'signup' %}" id="signup" class="text-success">Sign up here</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

BookStore3/users/templates/users/logout.html
<!-- This will inherit from the __base.html located in this directory -->
<!-- The navbar will be located here -->
{% extends "storePage/partials/__base.html" %}
<!-- This is the main header and footer that all html will fallow by -->
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block body %}

<!-- This page will be displayed once user have logged out -->
<main role="main" class="container" style = "margin-top:40px">
    <div>
        <h1>You have logged out...</h1>
        <div class="border-top pt-4 border-primary">
            <!-- add link if you want to relog in -->
            <a href="{% url 'login' %}" class="text-success" style="font-size: 20px">
                Click Here To Log In Again!
            </a>
        </div>
    </div>
</main>
{% endblock %}