search/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
from .views import *

app_name = 'search'

urlpatterns = [
    path('', views.search_by_title, name='search'),
    path('title', views.search_by_title, name='title'),
    path('author', views.search_by_author, name='author'),
    path('price', views.search_by_price, name='price'),
    path('rating', views.search_by_rating, name='rating'),
    path('date', views.search_by_date, name='date'),
    path('genre', views.search_by_genre, name='genre'),
    path('browse-fantasy', views.browse_fantasy, name='browse-fantasy'),
    path('browse-fiction', views.browse_fiction, name='browse-fiction'),
    path('browse-nonfiction', views.browse_nonfiction, name='browse-nonfiction'),
    path('browse-mystery', views.browse_mystery, name='browse-mystery'),
    path('browse-romance', views.browse_romance, name='browse-romance'),
    path('browse-scifi', views.browse_top, name='browse-top'),
    path('browse-top', views.browse_scifi, name='browse-scifi'),
    path('rating>=1', views.search_by_rating1, name='rating1'),
    path('rating>=2', views.search_by_rating2, name='rating2'),
    path('rating>=3', views.search_by_rating3, name='rating3'),
    path('rating>=4', views.search_by_rating4, name='rating4'),
    path('rating>=5', views.search_by_rating5, name='rating5'),
    # path('', views.search_by_author, name='search_by_author'),
]

# from django.urls import path, include   # path is to create the path in urlpatterns
# from . import views # Import the views defined in the current directory

# Name of the app needed for the namespace on urls.py
# app_name = 'settings'

# # all settings urls!!!
# urlpatterns = [
#     path('', views.settingsHome, name='settings-home'),
#     path('profile/', views.profile, name='profile-settings'),
#     path('account/', views.accountSettings, name='account-settings'),
#     path('billing/', views.billingSettings, name='billing-settings'),
#     path('billing/address/new/', views.addAddress, name='add-address'),
#     path('billing/address/<slug:address_slug>/', views.addressChange, name='edit-address'),
#     path('billing/creditcard/new/', views.addCreditCard, name='add-creditcard'),
#     path('billing/creditcard/<slug:creditcard_slug>/', views.creditCardChange, name='edit-creditcard'),
#     path('security/', views.securitySettings, name='security-settings')
# ]

search/templates/search/searchTest_form.html
<form method="POST" action="/searchTest">
    {% csrf_token %}
    <input type="text" name="textfield">
    
    <button type="submit">Upload text</button>
    </form>

search/templates/search/search_base.html
<!-- This will inherit from the __base.html located in this directory -->
<!-- The navbar will be located here -->

{% extends "storePage/partials/__base.html" %}
<!-- This is the main header and footer that all html will fallow by -->
{% load crispy_forms_tags %}
<!-- This will make the form look better, less code. -->
{% block body %}

<!-- This page will allow the user to log in to their account -->

<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->

<style>
  /* .rating {
    unicode-bidi: bidi-override;
    direction: rtl;
  }

  .rating>span {
    display: inline-block;
    position: relative;
    width: 1.1em;
  }

  .rating>span:hover:before,
  .rating>span:hover~span:before {
    content: "\2605";
    position: absolute;
  } */
</style>
<!-- </head> -->
<!-- 
<body> -->
<!-- <div>
  <form action="genre-browse" method="post">
    <h4>Select the Genres you would like to browse:</h4>
    <input type="radio" name="genre" value="Fantasy"/>Fantasy
    <input type="radio" name="genre" value="Romance"/>Romance
    <input type="radio" name="genre" value="Sci-Fi"/>Sci-Fi<br>
    <input type="radio" name="genre" value="Fiction"/>Fiction
    <input type="radio" name="genre" value="Non-Fiction"/>Non-Fiction
    <input type="radio" name="genre" value="Mystery"/>Mystery<br>
    <input type="submit" value="Browse">
  </form>
</div> -->

<table style="width:100%">
  <tr>
    <th style="width:10%"><H5>Browse By Top Sellers: </H5></th>
    <th style="width:20%"><a href="{% url 'search:browse-top' %}"><H3>Top Sellers</H3></a></th>
  </tr>
  <tr>
    <th style="width:10%"><H5>Browse By Genre: </H5></th>
    <th style="width:20%"><a href="{% url 'search:browse-fantasy' %}">Fantasy</a></th>
    <th style="width:10%"><a href="{% url 'search:browse-fiction' %}">Fiction</a></th>
    <th style="width:10%"><a href="{% url 'search:browse-nonfiction' %}">Non-Fiction</a></th>
    <th style="width:10%"><a href="{% url 'search:browse-mystery' %}">Mystery</a></th>
    <th style="width:10%"><a href="{% url 'search:browse-romance' %}">Romance</a></th>
    <th style="width:10%"><a href="{% url 'search:browse-scifi' %}">Science-Fiction</a></th>
  </tr>
  <tr>
    <th style="width:10%">Cover</th>
    <th style="width:20%"><a href="{% url 'search:title' %}">Title</a></th>
    <th style="width:10%"><a href="{% url 'search:author' %}">Author</a></th>
    <th style="width:10%"><a href="{% url 'search:genre' %}">Genre</a></th>
    <th style="width:10%">Units Sold</th>
    <th style="width:10%">Rating
      <div class="rating">
        <span><a href="{% url 'search:rating1' %}">☆</a></span>
        <span><a href="{% url 'search:rating2' %}">☆</a></span>
        <span><a href="{% url 'search:rating3' %}">☆</a></span>
        <span><a href="{% url 'search:rating4' %}">☆</a></span>
        <span><a href="{% url 'search:rating5' %}">☆</a></span>
      </div>
    </th>
    <th style="width:10%"><a href="{% url 'search:price' %}">Price</a></th>
    <th style="width:10%"><a href="{% url 'search:date' %}">Release Date</a></th>
    <th style="width:20%">Description</th>
    {% for book in books %}
  </tr>
  <td><img src="{{ book.cover.url }}" width="50px"></td>
  <td><a href="/books/{{book.id}}">{{ book.bookName }}</a></td>
  <td>{{ book.authorName }}</td>
  <td>{{ book.genre }}</td>
  <td>{{ book.bookSales }}</td>
  <td>{{ book.bookRating }}</td>
  <td>{{ book.bookPrice }}</td>
  <td>{{ book.publisherDate }}</td>
  <td>{{ book.bookSummary}}</td>
  </tr>
  {% endfor %}
</table>

{% if books.has_other_pages %}
<ul class="pagination">
  {% if books.has_previous %}
  <li><a href="?page={{ books.previous_page_number }}">&laquo;</a></li>
  {% else %}
  <li class="disabled"><span>&laquo;</span></li>
  {% endif %}
  {% for i in books.paginator.page_range %}
  {% if books.number == i %}
  <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
  {% else %}
  <li><a href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if books.has_next %}
  <li><a href="?page={{ books.next_page_number }}">&raquo;</a></li>
  {% else %}
  <li class="disabled"><span>&raquo;</span></li>
  {% endif %}
</ul>
{% endif %}
<!-- </body> -->
{% endblock %}

search/templates/search/search_details.html
<!doctype html>
<html>
<head>
<style>
<h2>Search Details</h2>
table {
font-family: arial, sans-serif;
border-collapse: collapse;
width: 100%;
}

td, th {
border: 1px solid #dddddd;
text-align: left;
padding: 8px;
}

tr:nth-child(even) {
background-color: #dddddd;
}
</style>
</head>

<body>

    <h2>GeekText Browsing Table</h2>

    <table>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Genre</th>
        </tr>
        <tr>
            <td>Harry Potter</td>
            <td>J.K. Rowling</td>
            <td>Fiction</td>
        </tr>
        <tr>
            <td>The Communist Manifesto</td>
            <td>Karl Marx</td>
            <td>Politics</td>
        </tr>
        <tr>
            <td>The Wealth of Nations</td>
            <td>Adam Smith</td>
            <td>Fiction</td>
        </tr>
        <!-- <tr>
            <td>Island Trading</td>
            <td>Helen Bennett</td>
            <td>Nonfiction</td>
        </tr>
        <tr>
            <td>For Whom The Bell Tolls</td>
            <td>Earnest Hemmingway</td>
            <td>Fiction</td>
        </tr>
        <tr>
            <td>The Hitchhiker's Guide to the Galaxy</td>
            <td>Douglas Adams</td>
            <td>Sci-Fi</td> -->
        </tr>
    </table>

</table>

</body>
</html>


<!-- <table>
    {% for Book in page1 %}
    <tr>
        <td><strong>{{ Book.title }}</strong></td>
        <td>{{ Book.author }}</td>
    </tr>
    {% empty %}
    <tr>
        <td><strong>No Results</strong></td>
    </tr>
    {% endfor %}
    <table>
        <caption>Monthly savings</caption>
        <tr>
            <th>Month</th>
            <th>Savings</th>
        </tr>
        <tr>
            <td>January</td>
            <td>$100</td>
        </tr>
        <tr>
            <td>February</td>
            <td>$50</td>
        </tr>
    </table>
</table> -->