BookStore3/bookStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    # Administration
    path('admin/', admin.site.urls),

    # User authentication
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    # Navigation
    # home page

    path('books/', include('books.urls')),
    path('', include('search.urls')),
    # path('', include('books.urls')),

    # user profile setting page which will include security, user information, and billing
    path('settings/', include('users.urls', namespace='settings')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookStore3/books/urls.py
from django.urls import path
from . import views
from .views import BookDetailView, AuthorBookListView

urlpatterns = [
    # path('', BookListView.as_view(), name='book-browsing'),
    path('', views.index, name='book-browsing'),
    path('<int:pk>/', BookDetailView.as_view(), name='book-details'),
    path('user/<username>', AuthorBookListView.as_view(), name='author-browsing'),  
    path('booksPurchased/<int:id>/', views.ReviewView, name='book-details-purchased'),  
]

BookStore3/search/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
from .views import *

app_name = 'search'

urlpatterns = [
    path('', views.search_by_title, name='search'),
    path('title', views.search_by_title, name='title'),
    path('author', views.search_by_author, name='author'),
    path('price', views.search_by_price, name='price'),
    path('rating', views.search_by_rating, name='rating'),
    path('date', views.search_by_date, name='date'),
    path('genre', views.search_by_genre, name='genre'),
    path('rating>=1', views.search_by_rating1, name='rating1'),
    path('rating>=2', views.search_by_rating2, name='rating2'),
    path('rating>=3', views.search_by_rating3, name='rating3'),
    path('rating>=4', views.search_by_rating4, name='rating4'),
    path('rating>=5', views.search_by_rating5, name='rating5'),
    # path('', views.search_by_author, name='search_by_author'),
]

# from django.urls import path, include   # path is to create the path in urlpatterns
# from . import views # Import the views defined in the current directory

# Name of the app needed for the namespace on urls.py
# app_name = 'settings'

# # all settings urls!!!
# urlpatterns = [
#     path('', views.settingsHome, name='settings-home'),
#     path('profile/', views.profile, name='profile-settings'),
#     path('account/', views.accountSettings, name='account-settings'),
#     path('billing/', views.billingSettings, name='billing-settings'),
#     path('billing/address/new/', views.addAddress, name='add-address'),
#     path('billing/address/<slug:address_slug>/', views.addressChange, name='edit-address'),
#     path('billing/creditcard/new/', views.addCreditCard, name='add-creditcard'),
#     path('billing/creditcard/<slug:creditcard_slug>/', views.creditCardChange, name='edit-creditcard'),
#     path('security/', views.securitySettings, name='security-settings')
# ]

BookStore3/storePage/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='store-home-page'),
]

BookStore3/users/urls.py
from django.urls import path, include   # path is to create the path in urlpatterns
from . import views # Import the views defined in the current directory

# Name of the app needed for the namespace on urls.py
app_name = 'settings'

# all settings urls!!!
urlpatterns = [
    path('', views.settingsHome, name='settings-home'),
    path('profile/', views.profile, name='profile-settings'),
    path('account/', views.accountSettings, name='account-settings'),
    path('billing/', views.billingSettings, name='billing-settings'),
    path('billing/address/new/', views.addAddress, name='add-address'),
    path('billing/address/<slug:address_slug>/', views.addressChange, name='edit-address'),
    path('billing/creditcard/new/', views.addCreditCard, name='add-creditcard'),
    path('billing/creditcard/<slug:creditcard_slug>/', views.creditCardChange, name='edit-creditcard'),
    path('security/', views.securitySettings, name='security-settings')
]

BookStore3/storePage/models.py
from django.db import models

BookStore3/storePage/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect


def index(request):
    # return response
    return HttpResponse("This is the home page")

BookStore3/storePage/templates/storePage/partials/__base.html
{% load static %}
<!-- This is the navbar that every section should get, in every page this should be at the top the header
      Look at my examples to understand how to use
-->
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Book Store CEN4010!</title>

    <!-- Font Awesome for different fonts-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <!-- We using Bootstrap version 4 core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body class="bg-dark text-white">

    <!--Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top " >
      {% if user.is_authenticated %}
        <!--if user is authorized then add this icon next to book meaning user has logged in-->
        <!-- search:search -->
        <a class="navbar-brand" href="{% url 'book-browsing' %}"><i class="fas fa-user fa-fw"></i>GeekText</a>
      {% else %}
        <a class="navbar-brand" href="{% url 'book-browsing' %}">GeekText</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
        aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent-333">

        <ul class="navbar-nav ml-auto nav-flex-icons">
          {% if user.is_authenticated %}
            {% if user.is_superuser %}
              <a class="nav-item nav-link" href="/admin/"><i class="fas fa-users-cog"></i> Admin</a>
            {% endif %}
              <!--add your urls here when finished with section to redirect to your page-->
              <a class="nav-item nav-link"  href="{% url 'settings:profile-settings' %}"><i class="fas fa-cog"></i> Settings</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
              <a class="nav-item nav-link" href="{% url 'search:title' %}"><i class="fa fa-search"></i> Browse</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Login</a>
          {% endif %}
        </ul>
      </div>
    </nav>
    <!--/.Navbar -->

    <!--The main body of the rest of the pages belong here-->
    <main role="main" style="margin-right: 30px; margin-left: 30px;">
      {% block body %} {% endblock %}
    </main>

    <!--For script-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
  </body>
</html>